In [1]:
import os, sys, random
import xml.etree.ElementTree as ET
import mxnet as mx
import cv2
from matplotlib import pyplot as plt
import numpy as np
import os
import pandas as pd
import random
from skimage import io
from shutil import copyfile
import sys
import time

import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array

In [2]:
# training annotation file
training_annotation_loc = r'D:\uc file\Intern ship\projects\data\OIDv4_ToolKit\OID\csv_folder\train-annotations-bbox.csv'
training_annotation_file = pd.read_csv(training_annotation_loc)
print("records present for training : ",training_annotation_file.shape)
training_annotation_file.head()

records present for training :  (14610229, 13)


ImageID  Source  LabelName  Confidence      XMin      XMax  \
0  000002b66c9c498e  xclick  /m/01g317           1  0.012500  0.195312   
1  000002b66c9c498e  xclick  /m/01g317           1  0.025000  0.276563   
2  000002b66c9c498e  xclick  /m/01g317           1  0.151562  0.310937   
3  000002b66c9c498e  xclick  /m/01g317           1  0.256250  0.429688   
4  000002b66c9c498e  xclick  /m/01g317           1  0.257812  0.346875   

       YMin      YMax  IsOccluded  IsTruncated  IsGroupOf  IsDepiction  \
0  0.148438  0.587500           0            1          0            0   
1  0.714063  0.948438           0            1          0            0   
2  0.198437  0.590625           1            0          0            0   
3  0.651563  0.925000           1            0          0            0   
4  0.235938  0.385938           1            0          0            0   

   IsInside  
0         0  
1         0  
2         0  
3         0  
4         0

In [3]:
# The class-descriptions-boxable.csv contains the name of all 600 classes with their corresponding ‘LabelName’
class_descriptions_file=r'D:\uc file\Intern ship\projects\data\OIDv4_ToolKit\OID\csv_folder\class-descriptions-boxable.csv'
class_descriptions = pd.read_csv(class_descriptions_file, header=None)
print(class_descriptions.shape)
class_descriptions.head()

(601, 2)


0           1
0    /m/011k07    Tortoise
1  /m/011q46kg   Container
2    /m/012074      Magpie
3    /m/0120dh  Sea turtle
4    /m/01226z    Football

In [4]:
# Find the label_name for 'Apple', 'Orange' and 'Light Switches' classes
Laptop = class_descriptions[class_descriptions[1]=='Laptop']
Mobile_phone = class_descriptions[class_descriptions[1]=='Mobile phone']

Laptop


label_name_Laptop = Laptop[0].values[0]
label_name_Mobile_phone = Mobile_phone[0].values[0]

In [5]:
Mobile_phone

0             1
312  /m/050k8  Mobile phone

In [6]:
Laptop

0       1
54  /m/01c648  Laptop

In [7]:
Laptop_bbox = training_annotation_file[training_annotation_file['LabelName']==label_name_Laptop]
Mobile_phone_bbox = training_annotation_file[training_annotation_file['LabelName']==label_name_Mobile_phone]
Mobile_phone_bbox


ImageID     Source LabelName  Confidence      XMin  \
1149      0000b9115cdf1e54     xclick  /m/050k8           1  0.095703   
2487      00016982f6086d39     xclick  /m/050k8           1  0.000000   
3963      0002a1a755d730ca     xclick  /m/050k8           1  0.178125   
5408      000384bb6da4764b     xclick  /m/050k8           1  0.695545   
8040      0005829bfcf77ca3     xclick  /m/050k8           1  0.611875   
...                    ...        ...       ...         ...       ...   
14602894  ffd92391b7d03016  activemil  /m/050k8           1  0.798437   
14604511  ffe1e233465f0a49  activemil  /m/050k8           1  0.025602   
14609308  fffa17e6456b26d6  activemil  /m/050k8           1  0.224771   
14609730  fffcbc0b28c934f7  activemil  /m/050k8           1  0.078750   
14609731  fffcbc0b28c934f7     xclick  /m/050k8           1  0.386875   

              XMax      YMin      YMax  IsOccluded  IsTruncated  IsGroupOf  \
1149      0.707031  0.497396  0.949219           0            0          0   
2487      0.997222  0.000000  0.998438           0            1          0   
3963      0.409375  0.339583  0.695833           1            0          0   
5408      0.985148  0.434375  0.803750           0            0          0   
8040      0.699375  0.585458  0.787535           1            0          0   
...            ...       ...       ...         ...          ...        ...   
14602894  0.964063  0.392188  0.531250           0            1          0   
14604511  0.944277  0.040493  0.917253           0            1          0   
14609308  0.872477  0.139375  0.801250           1            0          0   
14609730  0.292500  0.176667  0.615833           0            0          0   
14609731  0.557500  0.189167  0.616667           1            0          0   

          IsDepiction  IsInside  
1149                0         0  
2487                0         0  
3963                0         0  
5408                0         0  
8040                0         0  
...               ...       ...  
14602894            0         0  
14604511            0         0  
14609308            0         0  
14609730            1         0  
14609731            1         0  

[6365 rows x 13 columns]

In [8]:
print('There are %d apples in the dataset' %(len(Laptop_bbox)))
print('There are %d oranges in the dataset' %(len(Mobile_phone_bbox)))

There are 9327 apples in the dataset
There are 6365 oranges in the dataset


In [9]:
Laptop_id = Laptop_bbox['ImageID']
Mobile_phone_id = Mobile_phone_bbox['ImageID']
Laptop_id.count() # 627 different ids are present
Laptop_id  # these are the details of 627 different ids present in apple_img_id

583         000060e3121c7305
3539        00022a6311159428
4018        0002af997ecdfcf4
5473        000396ae942e8778
6449        00048edce2a37368
                  ...       
14602447    ffd6aa9288085a8f
14604500    ffe1bfb06dd60d55
14605390    ffe4ab4dc71ccaa3
14605393    ffe4ab4dc71ccaa3
14610134    ffff83c6a0e1c6c0
Name: ImageID, Length: 9327, dtype: object

In [10]:
concated_df=pd.concat([Laptop_bbox, Mobile_phone_bbox], axis=0)
concated_df

ImageID     Source  LabelName  Confidence      XMin  \
583       000060e3121c7305     xclick  /m/01c648           1  0.322500   
3539      00022a6311159428     xclick  /m/01c648           1  0.126875   
4018      0002af997ecdfcf4     xclick  /m/01c648           1  0.250000   
5473      000396ae942e8778     xclick  /m/01c648           1  0.000000   
6449      00048edce2a37368     xclick  /m/01c648           1  0.000000   
...                    ...        ...        ...         ...       ...   
14602894  ffd92391b7d03016  activemil   /m/050k8           1  0.798437   
14604511  ffe1e233465f0a49  activemil   /m/050k8           1  0.025602   
14609308  fffa17e6456b26d6  activemil   /m/050k8           1  0.224771   
14609730  fffcbc0b28c934f7  activemil   /m/050k8           1  0.078750   
14609731  fffcbc0b28c934f7     xclick   /m/050k8           1  0.386875   

              XMax      YMin      YMax  IsOccluded  IsTruncated  IsGroupOf  \
583       0.389375  0.580131  0.669166           0            0          0   
3539      0.484375  0.638281  0.871094           0            0          0   
4018      0.363750  0.236667  0.334444           0            0          0   
5473      0.995000  0.000000  0.996390           0            0          0   
6449      0.225000  0.710000  0.999167           1            1          0   
...            ...       ...       ...         ...          ...        ...   
14602894  0.964063  0.392188  0.531250           0            1          0   
14604511  0.944277  0.040493  0.917253           0            1          0   
14609308  0.872477  0.139375  0.801250           1            0          0   
14609730  0.292500  0.176667  0.615833           0            0          0   
14609731  0.557500  0.189167  0.616667           1            0          0   

          IsDepiction  IsInside  
583                 0         0  
3539                0         0  
4018                0         0  
5473                0         0  
6449                0         0  
...               ...       ...  
14602894            0         0  
14604511            0         0  
14609308            0         0  
14609730            1         0  
14609731            1         0  

[15692 rows x 13 columns]

In [11]:
concated_df['ClassName']=concated_df['LabelName']
concated_df['ClassName']

583         /m/01c648
3539        /m/01c648
4018        /m/01c648
5473        /m/01c648
6449        /m/01c648
              ...    
14602894     /m/050k8
14604511     /m/050k8
14609308     /m/050k8
14609730     /m/050k8
14609731     /m/050k8
Name: ClassName, Length: 15692, dtype: object

In [12]:
#classes = ['apple', 'orange', 'Light switch']
#labels = ['/m/014j1m', '/m/0cyhj_', '/m/03jbxj']


mapping = {
    '/m/01c648': 'Laptop',
    '/m/050k8': 'Mobile_phone',
}

concated_df['ClassName'] = [mapping[word] for word in concated_df['ClassName']]
concated_df['ClassName']

concated_df

ImageID     Source  LabelName  Confidence      XMin  \
583       000060e3121c7305     xclick  /m/01c648           1  0.322500   
3539      00022a6311159428     xclick  /m/01c648           1  0.126875   
4018      0002af997ecdfcf4     xclick  /m/01c648           1  0.250000   
5473      000396ae942e8778     xclick  /m/01c648           1  0.000000   
6449      00048edce2a37368     xclick  /m/01c648           1  0.000000   
...                    ...        ...        ...         ...       ...   
14602894  ffd92391b7d03016  activemil   /m/050k8           1  0.798437   
14604511  ffe1e233465f0a49  activemil   /m/050k8           1  0.025602   
14609308  fffa17e6456b26d6  activemil   /m/050k8           1  0.224771   
14609730  fffcbc0b28c934f7  activemil   /m/050k8           1  0.078750   
14609731  fffcbc0b28c934f7     xclick   /m/050k8           1  0.386875   

              XMax      YMin      YMax  IsOccluded  IsTruncated  IsGroupOf  \
583       0.389375  0.580131  0.669166           0            0          0   
3539      0.484375  0.638281  0.871094           0            0          0   
4018      0.363750  0.236667  0.334444           0            0          0   
5473      0.995000  0.000000  0.996390           0            0          0   
6449      0.225000  0.710000  0.999167           1            1          0   
...            ...       ...       ...         ...          ...        ...   
14602894  0.964063  0.392188  0.531250           0            1          0   
14604511  0.944277  0.040493  0.917253           0            1          0   
14609308  0.872477  0.139375  0.801250           1            0          0   
14609730  0.292500  0.176667  0.615833           0            0          0   
14609731  0.557500  0.189167  0.616667           1            0          0   

          IsDepiction  IsInside     ClassName  
583                 0         0        Laptop  
3539                0         0        Laptop  
4018                0         0        Laptop  
5473                0         0        Laptop  
6449                0         0        Laptop  
...               ...       ...           ...  
14602894            0         0  Mobile_phone  
14604511            0         0  Mobile_phone  
14609308            0         0  Mobile_phone  
14609730            1         0  Mobile_phone  
14609731            1         0  Mobile_phone  

[15692 rows x 14 columns]

In [13]:
# Data format for faster R-Cnn   :    ['FileName', 'XMin', 'XMax', 'YMin', 'YMax', 'ClassName'])
train_df= concated_df.loc[:,['ImageID','XMin','XMax','YMin','YMax','ClassName']]
train_df

ImageID      XMin      XMax      YMin      YMax  \
583       000060e3121c7305  0.322500  0.389375  0.580131  0.669166   
3539      00022a6311159428  0.126875  0.484375  0.638281  0.871094   
4018      0002af997ecdfcf4  0.250000  0.363750  0.236667  0.334444   
5473      000396ae942e8778  0.000000  0.995000  0.000000  0.996390   
6449      00048edce2a37368  0.000000  0.225000  0.710000  0.999167   
...                    ...       ...       ...       ...       ...   
14602894  ffd92391b7d03016  0.798437  0.964063  0.392188  0.531250   
14604511  ffe1e233465f0a49  0.025602  0.944277  0.040493  0.917253   
14609308  fffa17e6456b26d6  0.224771  0.872477  0.139375  0.801250   
14609730  fffcbc0b28c934f7  0.078750  0.292500  0.176667  0.615833   
14609731  fffcbc0b28c934f7  0.386875  0.557500  0.189167  0.616667   

             ClassName  
583             Laptop  
3539            Laptop  
4018            Laptop  
5473            Laptop  
6449            Laptop  
...                ...  
14602894  Mobile_phone  
14604511  Mobile_phone  
14609308  Mobile_phone  
14609730  Mobile_phone  
14609731  Mobile_phone  

[15692 rows x 6 columns]

In [14]:
train_df['ImageID']=train_df['ImageID']+'.jpg'
train_df

ImageID      XMin      XMax      YMin      YMax  \
583       000060e3121c7305.jpg  0.322500  0.389375  0.580131  0.669166   
3539      00022a6311159428.jpg  0.126875  0.484375  0.638281  0.871094   
4018      0002af997ecdfcf4.jpg  0.250000  0.363750  0.236667  0.334444   
5473      000396ae942e8778.jpg  0.000000  0.995000  0.000000  0.996390   
6449      00048edce2a37368.jpg  0.000000  0.225000  0.710000  0.999167   
...                        ...       ...       ...       ...       ...   
14602894  ffd92391b7d03016.jpg  0.798437  0.964063  0.392188  0.531250   
14604511  ffe1e233465f0a49.jpg  0.025602  0.944277  0.040493  0.917253   
14609308  fffa17e6456b26d6.jpg  0.224771  0.872477  0.139375  0.801250   
14609730  fffcbc0b28c934f7.jpg  0.078750  0.292500  0.176667  0.615833   
14609731  fffcbc0b28c934f7.jpg  0.386875  0.557500  0.189167  0.616667   

             ClassName  
583             Laptop  
3539            Laptop  
4018            Laptop  
5473            Laptop  
6449            Laptop  
...                ...  
14602894  Mobile_phone  
14604511  Mobile_phone  
14609308  Mobile_phone  
14609730  Mobile_phone  
14609731  Mobile_phone  

[15692 rows x 6 columns]

In [15]:
train_df.shape
train_df.to_csv('train.csv')
train_df['ClassName'].value_counts()

Laptop          9327
Mobile_phone    6365
Name: ClassName, dtype: int64

In [40]:
# Writing train.csv to annotation.txt

train_df = pd.read_csv('train.csv')

# for training
with open("annotation.txt", "w+") as f:
  for idx, row in train_df.iterrows():
    img = cv2.imread('D:/uc file/Intern ship/projects/month/Fast_RCNN/datanew/' + row['ImageID'])
    if(img is not None):
        
#         print(img)  #none 
        height, width = img.shape[:2]
        x1 = int(row['XMin'] * width)
        x2 = int(row['XMax'] * width)
        y1 = int(row['YMin'] * height)
        y2 = int(row['YMax'] * height)
      
        train_file_path = 'D:/uc file/Intern ship/projects/month/Fast_RCNN/train'
        fileName = os.path.join(train_file_path, row['ImageID'])
        className = row['ClassName']
        f.write(fileName + ',' + str(x1) + ',' + str(y1) + ',' + str(x2) + ',' + str(y2) + ',' + className + '\n')

[[[181 177 189]
  [181 177 188]
  [180 176 187]
  ...
  [ 29 117 177]
  [ 28 116 176]
  [ 27 115 175]]

 [[181 177 189]
  [180 176 187]
  [180 177 186]
  ...
  [ 31 119 179]
  [ 30 118 178]
  [ 29 117 177]]

 [[180 176 187]
  [180 177 186]
  [178 177 186]
  ...
  [ 34 122 182]
  [ 32 120 180]
  [ 31 119 179]]

 ...

 [[171 162 172]
  [115 106 116]
  [ 78  69  79]
  ...
  [ 95 100 139]
  [104 108 149]
  [ 53  59 100]]

 [[184 175 185]
  [125 116 126]
  [ 84  75  85]
  ...
  [102 101 135]
  [119 117 153]
  [ 92  90 126]]

 [[189 180 190]
  [147 138 148]
  [ 92  83  93]
  ...
  [133 124 151]
  [117 105 133]
  [212 200 228]]]
[[[122  90  31]
  [115  84  33]
  [111  80  41]
  ...
  [ 21  79 114]
  [ 23  76 109]
  [ 28  79 112]]

 [[117  87  32]
  [112  82  33]
  [112  79  40]
  ...
  [ 18  78 114]
  [ 20  75 112]
  [ 23  76 109]]

 [[115  87  33]
  [115  84  33]
  [106  77  33]
  ...
  [ 20  78 113]
  [ 25  77 113]
  [ 26  78 108]]

 ...

 [[ 45  49  54]
  [ 48  53  56]
  [ 50  55  58]
  ..

[[[  0  67 120]
  [  3  70 119]
  [  0  72 128]
  ...
  [251 253 253]
  [251 253 253]
  [251 253 253]]

 [[  1  65 123]
  [  1  66 117]
  [  0  70 123]
  ...
  [250 252 252]
  [251 253 253]
  [251 253 253]]

 [[  2  67 122]
  [  0  69 119]
  [  1  67 118]
  ...
  [251 253 253]
  [251 253 253]
  [251 253 253]]

 ...

 [[  1 119 202]
  [  1 117 201]
  [  1 117 202]
  ...
  [  0   5  14]
  [  1   6  15]
  [  0   5  12]]

 [[  1 117 202]
  [  0 116 201]
  [  0 115 200]
  ...
  [  1   5  16]
  [  2   7  16]
  [  1   6  15]]

 [[  1 114 200]
  [  0 116 201]
  [  0 119 204]
  ...
  [  1   5  16]
  [  0   5  14]
  [  1   6  15]]]
[[[138 132 127]
  [136 130 125]
  [137 131 126]
  ...
  [121 120 116]
  [117 121 115]
  [117 125 115]]

 [[134 132 122]
  [134 131 123]
  [135 131 126]
  ...
  [125 121 120]
  [120 122 116]
  [119 121 115]]

 [[131 131 119]
  [133 132 122]
  [131 131 125]
  ...
  [126 121 120]
  [125 122 118]
  [123 120 116]]

 ...

 [[ 82  83  81]
  [ 85  83  82]
  [ 95  89  84]
  ..

[[[ 51  36  20]
  [ 49  37  19]
  [ 53  39  21]
  ...
  [239  48   0]
  [238  47   0]
  [238  47   0]]

 [[ 46  33  17]
  [ 50  35  19]
  [ 52  38  20]
  ...
  [242  48   0]
  [238  48   0]
  [238  47   0]]

 [[ 51  35  22]
  [ 51  37  19]
  [ 50  36  17]
  ...
  [239  49   0]
  [238  48   0]
  [238  48   0]]

 ...

 [[155 207 224]
  [155 207 224]
  [156 208 225]
  ...
  [130 147 168]
  [125 142 161]
  [119 134 153]]

 [[152 206 223]
  [152 206 223]
  [155 207 224]
  ...
  [108 127 148]
  [100 117 138]
  [ 94 108 127]]

 [[152 205 225]
  [149 205 222]
  [152 206 223]
  ...
  [ 86 104 121]
  [ 76  91 110]
  [ 65  80  99]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

[[[253 242 250]
  [243 229 240]
  [213 187 205]
  ...
  [ 39  55 114]
  [ 32  57 119]
  [ 34  63 124]]

 [[222 177 196]
  [204 160 183]
  [174 123 151]
  ...
  [ 37  51 109]
  [ 40  60 118]
  [ 41  65 125]]

 [[161  89 119]
  [150  78 114]
  [136  59  97]
  ...
  [ 36  47 107]
  [ 46  60 126]
  [ 37  56 123]]

 ...

 [[ 85 208 128]
  [ 93 205 127]
  [ 93 202 123]
  ...
  [253 255 255]
  [253 255 255]
  [253 255 255]]

 [[ 92 213 132]
  [ 92 202 124]
  [ 96 202 125]
  ...
  [253 255 255]
  [253 255 255]
  [253 255 255]]

 [[ 93 213 132]
  [ 92 198 121]
  [ 88 195 116]
  ...
  [253 255 255]
  [253 255 255]
  [253 255 255]]]
[[[161 159 165]
  [160 158 164]
  [156 155 159]
  ...
  [249 244 241]
  [249 244 241]
  [249 244 241]]

 [[224 211 213]
  [210 197 199]
  [188 177 179]
  ...
  [249 244 241]
  [249 244 241]
  [249 244 241]]

 [[250 239 235]
  [252 241 237]
  [251 240 236]
  ...
  [249 244 241]
  [250 245 242]
  [250 245 242]]

 ...

 [[ 31  19  17]
  [ 30  18  16]
  [ 31  19  17]
  ..

[[[144 166 177]
  [144 166 177]
  [145 167 178]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 [[141 163 174]
  [141 163 174]
  [142 164 175]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 [[136 158 169]
  [136 158 169]
  [137 159 170]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 ...

 [[ 36  33  29]
  [ 31  28  24]
  [ 23  20  16]
  ...
  [230 225 224]
  [231 225 226]
  [230 225 226]]

 [[ 34  31  27]
  [ 29  26  22]
  [ 22  19  15]
  ...
  [227 222 221]
  [227 222 223]
  [227 222 223]]

 [[ 30  28  27]
  [ 25  23  22]
  [ 17  15  14]
  ...
  [225 220 219]
  [224 219 220]
  [224 219 220]]]
[[[144 166 177]
  [144 166 177]
  [145 167 178]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 [[141 163 174]
  [141 163 174]
  [142 164 175]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 [[136 158 169]
  [136 158 169]
  [137 159 170]
  ...
  [101 111 111]
  [101 111 111]
  [101 111 111]]

 ...

 [[ 36  33  29]
  [ 31  28  24]
  [ 23  20  16]
  ..

[[[214 208 185]
  [224 218 195]
  [234 226 203]
  ...
  [142 141 113]
  [155 152 124]
  [157 154 126]]

 [[211 205 182]
  [221 215 192]
  [231 223 200]
  ...
  [148 147 119]
  [161 158 130]
  [163 160 132]]

 [[206 200 177]
  [217 211 188]
  [228 220 197]
  ...
  [150 147 119]
  [160 158 128]
  [163 161 131]]

 ...

 [[ 80  85  84]
  [ 73  78  77]
  [ 73  78  77]
  ...
  [185 173 155]
  [186 174 156]
  [185 173 155]]

 [[ 75  80  79]
  [ 70  75  74]
  [ 70  75  74]
  ...
  [206 194 176]
  [181 169 151]
  [181 169 151]]

 [[ 79  84  83]
  [ 75  80  79]
  [ 74  79  78]
  ...
  [202 190 172]
  [178 166 148]
  [180 168 150]]]
[[[ 15  20  23]
  [ 11  16  19]
  [ 15  19  20]
  ...
  [201 222 243]
  [202 226 246]
  [198 222 242]]

 [[ 21  26  29]
  [ 13  18  21]
  [ 14  18  19]
  ...
  [202 223 244]
  [202 226 246]
  [199 223 243]]

 [[ 22  27  30]
  [ 14  19  22]
  [ 15  20  21]
  ...
  [202 223 244]
  [201 225 245]
  [197 221 241]]

 ...

 [[ 12  13  17]
  [ 14  15  19]
  [ 14  15  19]
  ..

[[[ 47 120  88]
  [ 54 126  96]
  [ 66 132 107]
  ...
  [134 128 133]
  [136 129 134]
  [139 130 133]]

 [[ 43 116  84]
  [ 56 126  96]
  [ 70 136 111]
  ...
  [131 129 135]
  [133 129 134]
  [137 131 136]]

 [[ 38 109  76]
  [ 54 124  93]
  [ 71 138 111]
  ...
  [129 134 143]
  [128 131 139]
  [130 134 139]]

 ...

 [[ 78  42  34]
  [ 74  41  32]
  [ 72  38  32]
  ...
  [128  73   4]
  [124  69   2]
  [122  67   0]]

 [[ 68  30  25]
  [ 64  28  22]
  [ 60  23  19]
  ...
  [126  71   2]
  [122  67   0]
  [119  64   0]]

 [[ 58  20  15]
  [ 55  17  12]
  [ 48  11   7]
  ...
  [124  70   0]
  [121  66   0]
  [119  64   0]]]
[[[  2 236 254]
  [  0 232 254]
  [  0 227 252]
  ...
  [  5   4   8]
  [  1   3   4]
  [  1   4   8]]

 [[  1 236 255]
  [  0 231 255]
  [  0 227 255]
  ...
  [  7  10  14]
  [  2   7  10]
  [  1   6   9]]

 [[  0 236 253]
  [  0 232 254]
  [  0 229 255]
  ...
  [  2   6  11]
  [  3   7  12]
  [  1   4   9]]

 ...

 [[  3  19  12]
  [  0  17  13]
  [  1  15  11]
  ..

[[[  7   4   6]
  [  5   2   4]
  [  6   3   5]
  ...
  [104 126  78]
  [102 125  70]
  [100 124  66]]

 [[ 11   6   8]
  [ 10   5   7]
  [  9   4   6]
  ...
  [103 125  76]
  [102 125  73]
  [103 125  73]]

 [[ 12   5  10]
  [ 11   4   9]
  [  9   2   5]
  ...
  [105 124  73]
  [106 125  76]
  [110 126  78]]

 ...

 [[ 32  30  22]
  [ 37  33  28]
  [ 32  28  23]
  ...
  [ 63  75  85]
  [ 62  74  84]
  [ 61  73  85]]

 [[ 35  35  29]
  [ 35  32  27]
  [ 31  28  24]
  ...
  [ 64  77  85]
  [ 65  75  85]
  [ 63  73  83]]

 [[ 28  31  29]
  [ 29  30  28]
  [ 30  30  30]
  ...
  [ 65  76  84]
  [ 65  76  84]
  [ 67  76  86]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

[[[181 205 225]
  [181 205 225]
  [180 204 224]
  ...
  [ 58  30  50]
  [ 57  28  51]
  [ 58  27  54]]

 [[183 207 227]
  [182 206 226]
  [181 205 225]
  ...
  [ 56  28  47]
  [ 55  26  49]
  [ 54  25  51]]

 [[184 208 228]
  [184 208 228]
  [183 207 227]
  ...
  [ 55  27  46]
  [ 55  27  47]
  [ 56  27  52]]

 ...

 [[ 63  27  33]
  [ 60  23  31]
  [ 58  22  34]
  ...
  [221 209 209]
  [221 209 209]
  [221 208 206]]

 [[ 62  26  32]
  [ 60  23  31]
  [ 58  22  34]
  ...
  [221 209 209]
  [221 209 209]
  [221 208 206]]

 [[ 60  24  30]
  [ 60  23  31]
  [ 59  23  35]
  ...
  [221 209 209]
  [221 209 209]
  [220 207 205]]]
[[[181 205 225]
  [181 205 225]
  [180 204 224]
  ...
  [ 58  30  50]
  [ 57  28  51]
  [ 58  27  54]]

 [[183 207 227]
  [182 206 226]
  [181 205 225]
  ...
  [ 56  28  47]
  [ 55  26  49]
  [ 54  25  51]]

 [[184 208 228]
  [184 208 228]
  [183 207 227]
  ...
  [ 55  27  46]
  [ 55  27  47]
  [ 56  27  52]]

 ...

 [[ 63  27  33]
  [ 60  23  31]
  [ 58  22  34]
  ..

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ...
  [ 66  79  81]
  [ 56  68  70]
  [ 57  66  69]]

 [[111 116 117]
  [107 115 115]
  [124 133 136]
  ...
  [ 73  84  88]
  [ 52  63  67]
  [ 61  72  76]]

 [[167 173 172]
  [145 153 152]
  [149 156 159]
  ...
  [ 60  71  75]
  [ 68  79  83]
  [ 76  87  91]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ..

[[[192 208 215]
  [192 208 215]
  [192 208 215]
  ...
  [182 192 199]
  [181 193 199]
  [179 191 197]]

 [[192 208 215]
  [192 208 215]
  [192 208 215]
  ...
  [181 191 198]
  [182 192 199]
  [181 191 198]]

 [[192 207 216]
  [192 207 216]
  [192 207 216]
  ...
  [181 191 198]
  [181 191 198]
  [181 191 198]]

 ...

 [[193 232 247]
  [197 233 249]
  [199 234 248]
  ...
  [120 154 183]
  [115 135 153]
  [ 76  89 105]]

 [[191 232 247]
  [195 234 249]
  [197 233 249]
  ...
  [119 153 182]
  [115 135 153]
  [ 75  85 102]]

 [[188 231 246]
  [192 233 248]
  [197 234 248]
  ...
  [118 150 179]
  [104 121 142]
  [ 65  73  90]]]
[[[192 208 215]
  [192 208 215]
  [192 208 215]
  ...
  [182 192 199]
  [181 193 199]
  [179 191 197]]

 [[192 208 215]
  [192 208 215]
  [192 208 215]
  ...
  [181 191 198]
  [182 192 199]
  [181 191 198]]

 [[192 207 216]
  [192 207 216]
  [192 207 216]
  ...
  [181 191 198]
  [181 191 198]
  [181 191 198]]

 ...

 [[193 232 247]
  [197 233 249]
  [199 234 248]
  ..

[[[ 5 11 10]
  [ 6 12 11]
  [ 8 14 13]
  ...
  [49 74 84]
  [48 73 83]
  [46 71 81]]

 [[ 5 11 10]
  [ 6 12 11]
  [ 7 13 12]
  ...
  [49 74 84]
  [48 73 83]
  [49 74 84]]

 [[ 6 12 11]
  [ 6 12 11]
  [ 6 12 11]
  ...
  [48 74 81]
  [48 74 81]
  [50 76 83]]

 ...

 [[ 4  2  2]
  [ 4  2  2]
  [ 3  3  3]
  ...
  [ 7  6  8]
  [ 9  8 10]
  [10  9 11]]

 [[ 2  2  2]
  [ 3  3  3]
  [ 5  5  5]
  ...
  [ 8  5  7]
  [ 9  6  8]
  [11  8 10]]

 [[ 2  2  2]
  [ 4  4  4]
  [ 6  6  6]
  ...
  [ 6  3  5]
  [ 7  4  6]
  [10  7  9]]]
[[[ 5 11 10]
  [ 6 12 11]
  [ 8 14 13]
  ...
  [49 74 84]
  [48 73 83]
  [46 71 81]]

 [[ 5 11 10]
  [ 6 12 11]
  [ 7 13 12]
  ...
  [49 74 84]
  [48 73 83]
  [49 74 84]]

 [[ 6 12 11]
  [ 6 12 11]
  [ 6 12 11]
  ...
  [48 74 81]
  [48 74 81]
  [50 76 83]]

 ...

 [[ 4  2  2]
  [ 4  2  2]
  [ 3  3  3]
  ...
  [ 7  6  8]
  [ 9  8 10]
  [10  9 11]]

 [[ 2  2  2]
  [ 3  3  3]
  [ 5  5  5]
  ...
  [ 8  5  7]
  [ 9  6  8]
  [11  8 10]]

 [[ 2  2  2]
  [ 4  4  4]
  [ 6  6  6]
  .

[[[20 32 34]
  [20 32 34]
  [20 32 34]
  ...
  [28 47 52]
  [28 47 52]
  [29 48 53]]

 [[20 32 34]
  [20 32 34]
  [20 32 34]
  ...
  [29 48 53]
  [29 48 53]
  [29 48 53]]

 [[20 32 34]
  [20 32 34]
  [21 33 35]
  ...
  [29 48 53]
  [29 48 53]
  [29 48 53]]

 ...

 [[ 3  2  4]
  [ 5  4  6]
  [ 6  5  7]
  ...
  [19 14 13]
  [20 15 14]
  [20 15 14]]

 [[ 3  2  4]
  [ 4  3  5]
  [ 5  4  6]
  ...
  [19 14 13]
  [20 15 14]
  [20 15 14]]

 [[ 2  1  3]
  [ 3  2  4]
  [ 4  3  5]
  ...
  [19 14 13]
  [20 15 14]
  [20 15 14]]]
[[[ 12  13  11]
  [ 11  13  13]
  [ 11  11  11]
  ...
  [ 35  39  44]
  [ 28  38  45]
  [ 27  37  44]]

 [[ 16  12  11]
  [ 16  11  12]
  [ 12  10   9]
  ...
  [ 32  41  45]
  [ 30  39  42]
  [ 32  39  42]]

 [[ 18  13  14]
  [ 16  14  14]
  [ 12  13  11]
  ...
  [ 33  42  46]
  [ 34  42  49]
  [ 36  38  48]]

 ...

 [[122 129 126]
  [129 132 130]
  [124 131 128]
  ...
  [180 179 175]
  [180 179 175]
  [181 178 173]]

 [[127 134 131]
  [126 133 130]
  [125 132 129]
  ...
  

[[[ 54  58  86]
  [ 57  56  88]
  [ 60  57  89]
  ...
  [ 21  35  53]
  [ 21  32  59]
  [ 24  31  56]]

 [[ 55  59  88]
  [ 54  56  86]
  [ 57  58  86]
  ...
  [ 24  30  65]
  [ 23  30  63]
  [ 24  31  56]]

 [[ 52  63  77]
  [ 57  63  86]
  [ 55  59  87]
  ...
  [ 21  32  59]
  [ 19  33  52]
  [ 18  30  54]]

 ...

 [[ 74  99 125]
  [ 69 103 126]
  [ 72 103 128]
  ...
  [ 68 118 154]
  [ 68 122 153]
  [ 72 120 148]]

 [[ 67  99 122]
  [ 70 101 124]
  [ 71 103 126]
  ...
  [ 71 117 148]
  [ 69 116 147]
  [ 70 115 152]]

 [[ 76  98 126]
  [ 72  96 124]
  [ 68  99 124]
  ...
  [ 69 116 148]
  [ 70 115 153]
  [ 60 109 153]]]
[[[135 143 150]
  [135 143 150]
  [135 143 150]
  ...
  [152 169 182]
  [151 168 181]
  [151 168 181]]

 [[136 144 151]
  [136 144 151]
  [136 144 151]
  ...
  [153 170 183]
  [152 169 182]
  [152 169 182]]

 [[136 144 151]
  [136 144 151]
  [137 145 152]
  ...
  [154 171 184]
  [153 170 183]
  [153 170 183]]

 ...

 [[  6   6   6]
  [  6   6   6]
  [  5   5   5]
  ..

[[[  5   1   0]
  [  5   1   0]
  [  2   0   0]
  ...
  [ 15  24  88]
  [ 16  25  89]
  [ 17  26  90]]

 [[  5   1   0]
  [  3   1   0]
  [  2   0   0]
  ...
  [ 15  23  90]
  [ 17  23  90]
  [ 16  24  91]]

 [[  3   1   1]
  [  2   0   0]
  [  2   0   0]
  ...
  [ 18  23  92]
  [ 20  22  92]
  [ 18  23  92]]

 ...

 [[156 166 176]
  [155 167 177]
  [155 170 179]
  ...
  [108  79 102]
  [102  72  97]
  [ 99  70  93]]

 [[156 166 176]
  [155 167 177]
  [155 170 179]
  ...
  [138 108 133]
  [133 103 128]
  [129  99 124]]

 [[157 166 176]
  [157 167 177]
  [157 169 179]
  ...
  [156 127 152]
  [152 123 148]
  [149 120 145]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

[[[124 164 176]
  [128 166 178]
  [134 172 184]
  ...
  [ 52  86 115]
  [ 51  85 114]
  [ 50  84 113]]

 [[170 199 204]
  [162 191 196]
  [151 179 186]
  ...
  [ 51  85 114]
  [ 52  86 115]
  [ 53  87 116]]

 [[189 209 210]
  [192 213 215]
  [195 218 220]
  ...
  [ 52  86 115]
  [ 53  87 116]
  [ 53  87 116]]

 ...

 [[148 183 196]
  [151 186 200]
  [150 185 199]
  ...
  [106 150 179]
  [110 154 183]
  [108 152 181]]

 [[149 184 197]
  [150 185 199]
  [150 183 198]
  ...
  [108 152 181]
  [110 154 183]
  [107 151 180]]

 [[152 186 199]
  [152 185 200]
  [150 183 198]
  ...
  [110 154 183]
  [108 152 181]
  [106 150 179]]]
[[[ 68  85 104]
  [ 67  84 103]
  [ 66  83 102]
  ...
  [ 97 116 131]
  [ 95 116 131]
  [ 95 116 131]]

 [[ 67  84 103]
  [ 67  84 103]
  [ 67  84 103]
  ...
  [100 119 134]
  [ 98 119 134]
  [ 98 119 134]]

 [[ 66  83 102]
  [ 67  84 103]
  [ 67  84 103]
  ...
  [101 120 135]
  [102 121 136]
  [102 121 136]]

 ...

 [[ 14  18  19]
  [ 12  16  17]
  [ 12  16  17]
  ..

[[[ 45  72  82]
  [ 42  69  79]
  [ 43  66  74]
  ...
  [ 50  45  46]
  [ 52  48  47]
  [ 54  50  49]]

 [[ 46  71  81]
  [ 40  66  73]
  [ 35  58  66]
  ...
  [ 48  43  44]
  [ 49  45  44]
  [ 51  47  46]]

 [[ 41  64  72]
  [ 37  60  68]
  [ 34  55  63]
  ...
  [ 46  41  42]
  [ 47  42  43]
  [ 48  43  44]]

 ...

 [[146 144 143]
  [147 145 144]
  [146 144 143]
  ...
  [149 145 144]
  [148 144 143]
  [148 144 143]]

 [[146 144 143]
  [148 146 145]
  [149 147 146]
  ...
  [150 146 145]
  [149 145 144]
  [150 146 145]]

 [[144 145 143]
  [147 148 146]
  [148 149 147]
  ...
  [150 146 145]
  [149 145 144]
  [150 146 145]]]
[[[215 210 207]
  [215 210 207]
  [217 212 209]
  ...
  [160 154 149]
  [160 153 150]
  [161 154 151]]

 [[217 212 209]
  [217 212 209]
  [218 213 210]
  ...
  [162 153 149]
  [160 154 149]
  [160 154 149]]

 [[219 214 211]
  [218 213 210]
  [218 213 210]
  ...
  [165 154 150]
  [162 153 149]
  [163 154 150]]

 ...

 [[212 209 204]
  [213 210 205]
  [214 211 206]
  ..

[[[ 70 103 122]
  [ 72 103 124]
  [ 76 102 126]
  ...
  [123 145 170]
  [131 150 171]
  [138 152 174]]

 [[ 66  99 119]
  [ 67  98 121]
  [ 72  98 122]
  ...
  [121 139 168]
  [128 139 169]
  [128 138 168]]

 [[ 62  96 119]
  [ 61  93 116]
  [ 65  94 115]
  ...
  [115 125 173]
  [113 123 170]
  [110 118 165]]

 ...

 [[184 186 216]
  [182 185 213]
  [182 186 210]
  ...
  [ 10   7  23]
  [ 10   7  23]
  [  8   5  21]]

 [[183 187 215]
  [183 188 213]
  [183 189 208]
  ...
  [ 10   7  22]
  [ 10   7  23]
  [  8   5  21]]

 [[180 185 218]
  [182 188 217]
  [184 190 213]
  ...
  [  8   8  22]
  [  9   9  23]
  [  7   7  21]]]
[[[112 139 160]
  [112 139 160]
  [111 138 159]
  ...
  [ 78 114 154]
  [ 78 112 155]
  [ 79 113 156]]

 [[110 137 158]
  [110 137 158]
  [109 136 157]
  ...
  [ 77 113 153]
  [ 78 112 155]
  [ 79 113 156]]

 [[109 136 157]
  [109 136 157]
  [109 136 157]
  ...
  [ 77 113 153]
  [ 77 113 153]
  [ 79 115 155]]

 ...

 [[103 140 162]
  [102 139 161]
  [102 139 161]
  ..

[[[ 12  94 166]
  [ 13  95 167]
  [ 14  96 168]
  ...
  [  2  72 139]
  [  4  72 139]
  [  6  74 141]]

 [[ 11  93 165]
  [ 12  94 166]
  [ 12  94 166]
  ...
  [  3  73 140]
  [  5  73 140]
  [  6  74 141]]

 [[ 10  92 164]
  [ 10  92 164]
  [ 10  92 164]
  ...
  [  3  73 140]
  [  3  73 140]
  [  5  75 142]]

 ...

 [[ 28  71 114]
  [ 24  67 110]
  [ 17  62 105]
  ...
  [  4  69 137]
  [  2  70 135]
  [  0  67 132]]

 [[ 29  72 115]
  [ 26  69 112]
  [ 20  65 108]
  ...
  [  4  69 137]
  [  1  69 134]
  [  0  66 131]]

 [[ 22  67 110]
  [ 21  66 109]
  [ 20  65 108]
  ...
  [  3  68 136]
  [  0  68 133]
  [  0  65 130]]]
[[[148 160 162]
  [148 160 162]
  [148 160 162]
  ...
  [166 171 174]
  [165 170 173]
  [165 170 173]]

 [[148 160 162]
  [148 160 162]
  [148 160 162]
  ...
  [166 171 174]
  [166 171 174]
  [165 170 173]]

 [[148 160 162]
  [148 160 162]
  [148 160 162]
  ...
  [166 171 174]
  [166 171 174]
  [166 171 174]]

 ...

 [[160 159 161]
  [160 159 161]
  [160 159 161]
  ..

[[[154 151 146]
  [155 152 147]
  [157 154 149]
  ...
  [ 55  48  39]
  [ 61  54  45]
  [ 67  58  49]]

 [[160 157 152]
  [162 159 154]
  [163 160 155]
  ...
  [ 57  50  41]
  [ 62  55  46]
  [ 68  59  50]]

 [[171 168 163]
  [173 170 165]
  [174 171 166]
  ...
  [ 59  51  44]
  [ 64  56  49]
  [ 66  58  51]]

 ...

 [[ 49  56  76]
  [ 48  55  74]
  [ 46  54  71]
  ...
  [ 14  14  26]
  [ 15  15  27]
  [ 16  16  28]]

 [[ 47  53  76]
  [ 47  54  74]
  [ 46  53  72]
  ...
  [ 14  14  26]
  [ 15  15  27]
  [ 15  15  27]]

 [[ 46  52  75]
  [ 46  53  73]
  [ 46  53  72]
  ...
  [ 14  14  26]
  [ 15  15  27]
  [ 15  15  27]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

[[[168 182 200]
  [168 182 200]
  [168 182 200]
  ...
  [126 147 174]
  [125 146 173]
  [125 146 173]]

 [[167 181 199]
  [167 181 199]
  [167 181 199]
  ...
  [127 148 175]
  [127 148 175]
  [127 148 175]]

 [[168 182 200]
  [168 182 200]
  [168 182 200]
  ...
  [126 147 174]
  [127 148 175]
  [127 148 175]]

 ...

 [[150 174 198]
  [150 174 198]
  [149 173 195]
  ...
  [154 176 201]
  [153 175 200]
  [153 175 200]]

 [[149 173 197]
  [149 173 197]
  [149 173 197]
  ...
  [154 176 201]
  [153 175 200]
  [153 175 200]]

 [[148 172 196]
  [148 172 196]
  [148 172 196]
  ...
  [153 175 200]
  [154 176 201]
  [154 176 201]]]
[[[126 151 161]
  [127 150 158]
  [130 152 158]
  ...
  [242 255 255]
  [241 255 254]
  [239 255 254]]

 [[125 147 158]
  [126 150 156]
  [129 151 157]
  ...
  [242 255 255]
  [241 255 254]
  [239 255 254]]

 [[131 151 162]
  [130 152 157]
  [129 151 157]
  ...
  [242 255 255]
  [241 255 254]
  [239 255 254]]

 ...

 [[ 46  53  56]
  [ 47  54  57]
  [ 48  55  58]
  ..

[[[ 88 104 103]
  [ 88 104 103]
  [ 87 103 102]
  ...
  [  2   0   0]
  [  2   0   0]
  [  2   0   0]]

 [[ 88 104 103]
  [ 87 103 102]
  [ 87 103 102]
  ...
  [  2   0   0]
  [  2   0   0]
  [  2   0   0]]

 [[ 87 103 102]
  [ 87 103 102]
  [ 87 103 102]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  4  42  74]
  [  4  42  74]
  [  5  43  75]
  ...
  [  7  10  14]
  [  8  11  15]
  [  9  12  16]]

 [[  3  41  73]
  [  4  42  74]
  [  5  43  75]
  ...
  [  7  10  14]
  [  6   9  13]
  [  7  10  14]]

 [[  3  41  73]
  [  4  42  74]
  [  5  43  75]
  ...
  [  6   9  13]
  [  6   9  13]
  [  7  10  14]]]
[[[100 100 100]
  [101 101 101]
  [100 100 100]
  ...
  [197 197 197]
  [198 198 198]
  [197 197 197]]

 [[101 101 101]
  [103 103 103]
  [101 101 101]
  ...
  [192 192 192]
  [192 192 192]
  [190 190 190]]

 [[ 99  99  99]
  [100 100 100]
  [102 102 102]
  ...
  [186 186 186]
  [187 187 187]
  [186 186 186]]

 ...

 [[215 215 215]
  [215 215 215]
  [213 213 213]
  ..

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ...
  [ 66  79  81]
  [ 56  68  70]
  [ 57  66  69]]

 [[111 116 117]
  [107 115 115]
  [124 133 136]
  ...
  [ 73  84  88]
  [ 52  63  67]
  [ 61  72  76]]

 [[167 173 172]
  [145 153 152]
  [149 156 159]
  ...
  [ 60  71  75]
  [ 68  79  83]
  [ 76  87  91]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ..

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ...
  [ 66  79  81]
  [ 56  68  70]
  [ 57  66  69]]

 [[111 116 117]
  [107 115 115]
  [124 133 136]
  ...
  [ 73  84  88]
  [ 52  63  67]
  [ 61  72  76]]

 [[167 173 172]
  [145 153 152]
  [149 156 159]
  ...
  [ 60  71  75]
  [ 68  79  83]
  [ 76  87  91]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ..

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ...
  [ 66  79  81]
  [ 56  68  70]
  [ 57  66  69]]

 [[111 116 117]
  [107 115 115]
  [124 133 136]
  ...
  [ 73  84  88]
  [ 52  63  67]
  [ 61  72  76]]

 [[167 173 172]
  [145 153 152]
  [149 156 159]
  ...
  [ 60  71  75]
  [ 68  79  83]
  [ 76  87  91]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ..

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ...
  [ 66  79  81]
  [ 56  68  70]
  [ 57  66  69]]

 [[111 116 117]
  [107 115 115]
  [124 133 136]
  ...
  [ 73  84  88]
  [ 52  63  67]
  [ 61  72  76]]

 [[167 173 172]
  [145 153 152]
  [149 156 159]
  ...
  [ 60  71  75]
  [ 68  79  83]
  [ 76  87  91]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 95 102 105]
  [100 107 110]
  [122 131 134]
  ..

[[[  5  26  71]
  [  6  27  72]
  [  7  27  74]
  ...
  [  9  90 151]
  [  3  83 144]
  [  7  87 148]]

 [[  3  25  67]
  [  4  26  68]
  [  4  26  68]
  ...
  [  9  90 151]
  [  6  86 147]
  [ 10  90 151]]

 [[  7  31  67]
  [  6  30  66]
  [  3  29  66]
  ...
  [  8  89 150]
  [  6  87 148]
  [ 10  91 152]]

 ...

 [[  6  16  33]
  [  3  13  31]
  [  2  10  33]
  ...
  [ 67  25  26]
  [ 53  20  24]
  [ 43  13  18]]

 [[  3  11  28]
  [  4  11  30]
  [  2  11  31]
  ...
  [ 74  20  25]
  [ 55  14  21]
  [ 48  14  21]]

 [[  4  12  29]
  [  5  12  31]
  [  2  11  31]
  ...
  [ 78  20  25]
  [ 58  13  22]
  [ 51  14  24]]]
[[[250 252 252]
  [253 255 255]
  [253 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[253 255 255]
  [249 251 251]
  [251 253 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[247 249 249]
  [250 252 252]
  [253 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 69  69  69]
  [ 69  69  69]
  [ 69  69  69]
  ..

[[[185 183 189]
  [185 183 189]
  [184 182 188]
  ...
  [176 178 179]
  [177 178 182]
  [177 178 182]]

 [[185 183 189]
  [185 183 189]
  [185 183 189]
  ...
  [178 180 181]
  [177 179 180]
  [175 177 178]]

 [[186 184 190]
  [186 184 190]
  [186 184 190]
  ...
  [178 180 180]
  [177 179 180]
  [175 177 178]]

 ...

 [[181 180 182]
  [181 180 182]
  [184 180 185]
  ...
  [173 173 173]
  [174 173 175]
  [174 173 175]]

 [[181 180 182]
  [181 180 182]
  [184 180 185]
  ...
  [173 173 173]
  [174 173 175]
  [175 174 176]]

 [[183 180 182]
  [184 181 183]
  [185 181 186]
  ...
  [173 172 174]
  [174 173 177]
  [175 174 178]]]
[[[ 9 18 21]
  [ 9 18 21]
  [ 9 18 21]
  ...
  [ 0 15 18]
  [ 4 19 22]
  [ 9 24 27]]

 [[ 9 18 21]
  [ 9 18 21]
  [ 9 18 21]
  ...
  [ 0 15 18]
  [ 3 18 21]
  [ 5 20 23]]

 [[ 9 18 21]
  [ 9 18 21]
  [ 9 18 21]
  ...
  [ 0 15 18]
  [ 1 16 19]
  [ 2 17 20]]

 ...

 [[ 4 16 18]
  [ 5 17 19]
  [ 5 17 19]
  ...
  [18 14 20]
  [19 15 21]
  [17 13 19]]

 [[ 7 16 19]
  [ 8 1

[[[126 146 181]
  [126 146 181]
  [128 147 182]
  ...
  [127 150 188]
  [124 150 187]
  [125 151 188]]

 [[126 146 181]
  [126 146 181]
  [126 146 181]
  ...
  [125 149 185]
  [124 150 186]
  [126 152 188]]

 [[126 146 181]
  [127 147 182]
  [125 145 180]
  ...
  [123 149 185]
  [124 150 186]
  [125 151 187]]

 ...

 [[ 54  34  29]
  [ 52  32  27]
  [ 55  33  28]
  ...
  [ 48  91 140]
  [ 49  92 141]
  [ 50  93 142]]

 [[ 52  33  28]
  [ 51  32  27]
  [ 52  32  27]
  ...
  [ 47  90 139]
  [ 51  92 141]
  [ 52  93 142]]

 [[ 51  33  26]
  [ 51  33  26]
  [ 52  32  27]
  ...
  [ 46  89 138]
  [ 51  92 141]
  [ 52  93 142]]]
[[[116 115 117]
  [118 117 119]
  [118 117 119]
  ...
  [ 98  95  97]
  [ 96  93  95]
  [ 95  92  94]]

 [[117 116 118]
  [120 119 121]
  [123 122 124]
  ...
  [ 98  95  97]
  [ 97  94  96]
  [ 96  93  95]]

 [[115 114 116]
  [119 118 120]
  [124 123 125]
  ...
  [ 98  95  97]
  [ 97  94  96]
  [ 97  94  96]]

 ...

 [[ 54  58  63]
  [ 52  56  61]
  [ 52  55  60]
  ..

[[[209 206 208]
  [211 208 210]
  [212 209 211]
  ...
  [ 34  55 206]
  [ 34  55 206]
  [ 34  55 206]]

 [[209 207 207]
  [211 209 209]
  [211 209 209]
  ...
  [ 33  54 205]
  [ 33  54 205]
  [ 34  55 206]]

 [[209 207 207]
  [211 209 209]
  [211 209 209]
  ...
  [ 31  52 203]
  [ 32  53 204]
  [ 33  54 205]]

 ...

 [[223 228 227]
  [222 227 226]
  [222 227 225]
  ...
  [212 212 212]
  [212 212 212]
  [211 211 211]]

 [[222 228 227]
  [221 227 226]
  [222 227 226]
  ...
  [212 212 212]
  [212 212 212]
  [211 211 211]]

 [[222 228 227]
  [221 227 226]
  [221 227 226]
  ...
  [212 212 212]
  [212 212 212]
  [212 212 212]]]
[[[209 206 208]
  [211 208 210]
  [212 209 211]
  ...
  [ 34  55 206]
  [ 34  55 206]
  [ 34  55 206]]

 [[209 207 207]
  [211 209 209]
  [211 209 209]
  ...
  [ 33  54 205]
  [ 33  54 205]
  [ 34  55 206]]

 [[209 207 207]
  [211 209 209]
  [211 209 209]
  ...
  [ 31  52 203]
  [ 32  53 204]
  [ 33  54 205]]

 ...

 [[223 228 227]
  [222 227 226]
  [222 227 225]
  ..

[[[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]

 [[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]

 [[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]

 ...

 [[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]

 [[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]

 [[201 255 255]
  [201 255 255]
  [201 255 255]
  ...
  [201 255 255]
  [201 255 255]
  [201 255 255]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  1 124 150]
  [  0 122 148]
  [  0 121 146]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  9 130 156]
  [  6 129 155]
  [  2 128 153]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 11 132 158]
  [  8 131 157]
  [  6 129 155]]

 ...

 [[  0   1  35]
  [  0   1  35]
  [  0   1  35]
  ..

[[[ 42  80  68]
  [ 40  77  67]
  [ 39  79  68]
  ...
  [ 56  74  81]
  [ 55  73  80]
  [ 56  74  81]]

 [[ 42  80  68]
  [ 40  80  68]
  [ 40  80  69]
  ...
  [ 57  75  82]
  [ 56  74  81]
  [ 56  74  81]]

 [[ 40  80  68]
  [ 42  82  70]
  [ 42  82  70]
  ...
  [ 54  72  79]
  [ 56  74  81]
  [ 58  77  82]]

 ...

 [[ 79 118 127]
  [ 79 118 127]
  [ 79 118 127]
  ...
  [ 64  79  88]
  [ 54  71  80]
  [ 55  71  83]]

 [[ 82 118 128]
  [ 79 118 127]
  [ 78 117 125]
  ...
  [ 70  85  94]
  [ 61  78  87]
  [ 54  70  82]]

 [[ 83 119 129]
  [ 80 117 125]
  [ 80 117 125]
  ...
  [ 71  86  95]
  [ 57  74  83]
  [ 57  73  85]]]
[[[ 78  83  82]
  [ 80  85  84]
  [ 82  87  88]
  ...
  [142 155 153]
  [141 154 152]
  [140 153 151]]

 [[ 80  85  84]
  [ 82  87  86]
  [ 84  89  90]
  ...
  [142 155 153]
  [141 154 152]
  [140 153 151]]

 [[ 82  88  87]
  [ 84  90  89]
  [ 87  93  92]
  ...
  [143 156 154]
  [142 155 153]
  [141 154 152]]

 ...

 [[138 123 120]
  [140 125 122]
  [143 128 125]
  ..

In [ ]:
# In the same way write annotation for test.csv
"""
test_df = pd.read_csv('test.csv')

# for test
with open("test_annotation.txt", "w+") as f:
  for idx, row in test_df.iterrows():
      sys.stdout.write(str(idx) + '\r')
      sys.stdout.flush()
      img = cv2.imread('test/' + row['ImgID'])
      height, width = img.shape[:2]
      x1 = int(row['XMin'] * width)
      x2 = int(row['XMax'] * width)
      y1 = int(row['YMin'] * height)
      y2 = int(row['YMax'] * height)
      
      test_file_path = 'D:/5-deep_learning_with_tensorflow/module 7 cnn/7-faster_r-cnn/Faster_r-cnn_demo_youtube/test'
      fileName = os.path.join(test_file_path, row['FileName'])
      className = row['ClassName']
      f.write(fileName + ',' + str(x1) + ',' + str(y1) + ',' + str(x2) + ',' + str(y2) + ',' + className + '\n')
      ""